language: android
sudo: false
jdk: oraclejdk8
android:
  components:
    - tools
    - platform-tools
    - build-tools-26.0.2
    - build-tools-27.0.3
    - android-24
    - android-26
    - android-27
    - extra-android-support
    - extra-android-m2repository
  licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+
script:
  ./gradlew build


